version: '3.3'

services:
  
  webserver:
    build: ./php
    ports: 
     - "30000:80"
#     - "443:443"
    volumes: 
     - ./src:/mysrc/
    depends_on: 
     - db
    environment:
     - PHP_EXTENSIONS=pdo_mysql
     - APACHE_DOCUMENT_ROOT /mysrc/

  db:
    image: mariadb:10.2
    restart: always
#    ports: 
#     - "3306:3306"
    volumes:
     - ./db:/lib/mysql
    environment: 
     - MYSQL_ROOT_PASSWORD=coucoucou
     - MYSQL_USER=bonjour
     - MYSQL_PASSWORD=coucoucou
     - MYSQL_DATABASE=test

  adminer:
    image: adminer
    restart: always
    ports: 
     - "50000:8080"
